### ISSUE TITLE
Implement 'Statistic Package'

### ISSUE THREAD

**Issue by minjk-bl** [visualpython/visualpython#69]
T-test, P-value ... etc included.

**Comment by naribro** [comment]
**- Progress Status on 25th Jul**
My team(Mr. Hyun-sub, Ho-jin, Jae-young) are preparing structure of statistics package 
for visual python and making list of stat methods.
Also for benchmarking other GUI based solutions such as SPSS, Rapidminer, Brightics Studio,
we are summarizing statistics method included in these solutions.

We plan to finish this work until this week and start to do make sample code for practice.

[Statistics Method List_Brightics Studio.xlsx](https://github.com/visualpython/visualpython/files/9180891/Statistics.Method.List_Brightics.Studio.xlsx)
[SPOILER_UNF_Statistics_Method_Rapidminer_Studio.xlsx](https://github.com/visualpython/visualpython/files/9180893/SPOILER_UNF_Statistics_Method_Rapidminer_Studio.xlsx)

**Comment by PFSV** [comment]
**-Progress Status on 7th August**

My team(Mr. Jae-young, Ho-jin, Hyun-sub) are focusing on fundamental statistical methods down below. 
1. Descriptive Statistics
2. Statistical Estimation
3. Statistical Analysis
4. Statistical Hypothesis Test

We are implementing basic functions of those categories starting from 8/1. Our first target is to implement ‘Analysis’. 
Since the logics are quite similar, the UI structure will be similar with ‘Machine learning-Regression section”
Our target is to make a package that convert those statistical functions above into Pandas dataframe, finally into Python codes.
(We will consider Numpy later)

Our task is 

1. find the intersection between statistical function of various solution 
2. make an app implement

We are now holding task No.1 and focusing on task No.2, by getting experimental appliance on visualpython js, html code.
We plan to make a sample code of Analysis part.

**Comment by PFSV** [comment]
-Progress Status on 8th August
My team(Mr.Ho-jin,Jae-young,Hyun-sub) has finished to list the benchmarked statistics GUI based solution packages.
After listing the whole packages, we found intersection of packages, which implies popular statistical methods that we should take focus upon them.
We are developing sample apps now, and a
[Statistics_Method.xlsx](https://github.com/visualpython/visualpython/files/9277199/Statistics_Method.xlsx)
re going to develop into real app according to the chart below, prioritised by green part of the chart.

**Comment by minjk-bl** [comment]
Updated.
